project:
  type: website

website:
  title: "Rose City Analytics"
  navbar:
    search: true
    right: 
      - text: Menu
        menu:
          - text: About
            href: about.qmd
          - text: Projects
            href: projects.qmd
          - text: Blog
            href: blog.qmd

format:
  html:
    theme: cosmo
    css: sty/styles.css
    toc: true



